/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jetbrains_skiko_java2d_Java2dCanvas */

#ifndef _Included_org_jetbrains_skiko_java2d_Java2dCanvas
#define _Included_org_jetbrains_skiko_java2d_Java2dCanvas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jetbrains_skiko_java2d_Java2dCanvas
 * Method:    createCanvasImpl
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jetbrains_skiko_java2d_Java2dCanvas_createCanvasImpl
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
